### ISSUE TITLE
Support for App Platform

### ISSUE THREAD

**Issue by WoLfulus** [pjpimentel/dots#100]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support for app platform requests.

**Is your request a new API endpoint?**
https://developers.digitalocean.com/documentation/v2/#apps

**Comment by pjpimentel** [comment]
@WoLfulus i have plans to implement those methods until next month.

**Comment by WoLfulus** [comment]
Do you have a checklist of what needs to be done in the project itself? Since I need this one ASAP, I can open a PR that implements it, just want to make sure it matches your project specs

Thanks!

**Comment by pjpimentel** [comment]
Sorry, not yet and I am not able to promise a date since I need to review the DO's docs.

Would be really cool if you open a PR with the main methods you need for now just following the pattern of other modules.

**Comment by pjpimentel** [comment]
@WoLfulus version 3.5.0 is available with "app module".
Any troubles feel free to open a new issue.
thanks!

**Comment by WoLfulus** [comment]
Hey! Thank you so much!

Sorry I wasn't able to do the PR!
