### ISSUE TITLE
Missing fields on App Platform types

### ISSUE THREAD

**Issue by rijkvanzanten** [pjpimentel/dots#102]
**Describe the bug**

I'm not allowed to read certain fields in the API response, like `in_progress_deployment`:

![CleanShot 2020-12-03 at 16 16 08](https://user-images.githubusercontent.com/9141017/101089245-e5a8d600-3582-11eb-8556-5b8cfd180c6a.png)

Even though the docs specify they exist (and they're returned when hitting the API manually):

https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-app

**Comment by pjpimentel** [comment]
hello @rijkvanzanten, thank you.

I'm going to take a look at the field "in_progress_deployment" soon is possible. What others fields did you notice that is missing? If you want to, feel free to open a PR fixing those types.

_Just note that any "type" issue can be by bypassed using the "any" in typescript (just for development, of course)_

**Comment by rijkvanzanten** [comment]
Sounds good! Just from a quick peak in the DO docs, it seems like the majority is missing. The only thing I'm not sure about is which of the fields are optional... DO only seems to return `in_progress_deployment` when there's an actual in progress deployment for example, but the whole key seems to be missing otherwise 🤔 

![CleanShot 2020-12-03 at 17 58 27](https://user-images.githubusercontent.com/9141017/101098597-2f002200-3591-11eb-982d-80f26ff35cf8.png)

**Comment by rijkvanzanten** [comment]
@pjpimentel PR coming right up :

**Comment by pjpimentel** [comment]
> Sounds good! Just from a quick peak in the DO docs, it seems like the majority is missing. The only thing I'm not sure about is which of the fields are optional... DO only seems to return `in_progress_deployment` when there's an actual in progress deployment for example, but the whole key seems to be missing otherwise 
> 
> ![CleanShot 2020-12-03 at 17 58 27](https://user-images.githubusercontent.com/9141017/101098597-2f002200-3591-11eb-982d-80f26ff35cf8.png)

yeah, my bad .
I was confused with the app platform types between this link: https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/ ; and the api docs.

**Comment by rijkvanzanten** [comment]
Yeah it can be quite confusing at times 😁 Especially seeing how quickly they're iterating on this new platform. Anywho, my pr should clean it up for the hopefully foreseeable future

**Comment by pjpimentel** [comment]
@rijkvanzanten version 3.5.1 being deployed, thank you!
