### ISSUE TITLE
Delete volume by name

### ISSUE THREAD

**Issue by ViktorWb** [pjpimentel/dots#109]
The DigitalOcean API supports [deleting a droplet by its name](https://developers.digitalocean.com/documentation/v2/#delete-a-block-storage-volume-by-name). This seems to not be supported by this library however.

For droplets, the following exists:

```
droplet.deleteDropletsByTag({ tag_name: "my tag" })
```

A similar method should exist, but for volumes and the volume name.

```
volume.deleteVolumeByName({ name: "my name", region: "fra1" })
```

**Comment by pjpimentel** [comment]
hey @ViktorWb

thanks for opening the issue :)

i will take a look at this request soon. 

if you want, feel free to open a PR.

**Comment by pjpimentel** [comment]
@ViktorWb 
version #3.5.4 available with "volume.deleteVolumeByName".

please, give me a feedback if its okay.

**Comment by ViktorWb** [comment]
Looks good! Thank you very much.
