### ISSUE TITLE
List Droplet By Tag

### ISSUE THREAD

**Issue by Daxcor69** [pjpimentel/dots#113]
**Is your feature request related to a problem? Please describe.**
I need the droplet ID, and the only way to query is by tag.

**Describe the solution you'd like**
try {
    const input = {
      per_page=2,
      page=1,
      tag_name: 'tagname',
    };
    const {
      data: { dropletId },
    } = await dots.droplet.listDroplets(input);
    console.log(dropletId);
  } catch (error) {
    console.log(error);
  }

**Describe alternatives you've considered**
Nothing yet. I would hate to have to shell out to use  doctl.

**Is your request a new API endpoint?**
https://docs.digitalocean.com/reference/api/api-reference/#operation/list_all_droplets

**Additional context**
Nope I think that gets it. My understanding there is no way to get a specific droplet ID without query the tag.

Brad

**Comment by pjpimentel** [comment]
hello Brad, @Daxcor69 

thanks for opening the issue! :) 

In the best of my knowledge, to you find the droplet id there's 3 ways:
1. list all droplets, page by page, and lookup for the one you want
2. list all droplets filtering by tag and, page by page, lookup for the one you want.
3. previously know the droplet id.

Just to be sure, what would you exactly do when you say: "use  doctl"?
What is the cmd you would run to find out the droplet id?

**Comment by Daxcor69** [comment]
Here is what I am using 
```
const getDropletId = async () => {
  const myConfig = {
    method: 'get',
    url: `https://api.digitalocean.com/v2/droplets?tag_name=${username}`,
    headers: {
      Authorization: `Bearer ${config.DIGITALOCEAN_TOKEN}`,
    },
  };

  const response = await axios(myConfig);
  const dropletId = response.data.droplets[0].id;
  return dropletId;
};
```
doctl was the wrong tool    :(

**Comment by Daxcor69** [comment]
I think your current enpoint would work, just need to add the tag_option

**Comment by pjpimentel** [comment]
yes, if you only need to list filtering by tag, you could use the "dots.droplet.listDroplets" method.

the following fn could do the same trick you described:

```javascript
const getDropletIdByTagName = async ({
   tag_name,
}) => {
  const input = {
    per_page: 2,
    page: 1,
    tag_name,
  };
  const {
    data: {
      droplets,
    } = {},
  } = await dots.droplet.listDroplets(input);
  const [first_droplet = {}] = droplets;
  const first_droplet_id = first_droplet.id;
  
  return first_droplet_id;
};
```

**Comment by Daxcor69** [comment]
console.log(getDropletIdByTagName(username));

When I do this, I get a pending as a response.  I am a beginner js guy. Not sure why inside the function, I get a value but outside I get pending.  Do I have to wrap this console.log line in another async function?

**Comment by pjpimentel** [comment]
yes, it is a async fn so you have to handle it.

```javascript
getDropletIdByTagName(username)
  .then((droplet_id) => console.log(droplet_id));
```

**Comment by Daxcor69** [comment]
thank you for that.

**Comment by pjpimentel** [comment]
no worries!

any troubles with the package, feel free to open a new issue.
