### ISSUE TITLE
TypeError: Cannot destructure property 'backups' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by say1j** [pjpimentel/dots#119]
When creating droplet with values from example getting next error (version 3.5.7):
TypeError: Cannot destructure property 'backups' of 'undefined' as it is undefined.
[dev] [2021-07-05 17:19:15]     at Object.createDroplet (/workspace/node_modules/dots-wrapper/dist/modules/droplet/create-droplet/create-droplet.js:4:47)
attributes to req:
![image](https://user-images.githubusercontent.com/31889581/124515628-906ac680-dde8-11eb-9e61-e57814312601.png)

**Comment by pjpimentel** [comment]
hey @say1j 

whats is the package version you are using?

plus, send me how you are calling the dots.droplet.createDroplet() please.

**Comment by say1j** [comment]
> hey @say1j
> 
> whats is the package version are you using?
> 
> plus, send me how you are calling the dots.droplet.createDroplet() please.

version 3.5.7 it was in issue text, attributes object on previous screenshot
![image](https://user-images.githubusercontent.com/31889581/124518739-e55e0b00-ddef-11eb-9405-83b7861c4de6.png)

**Comment by say1j** [comment]
@pjpimentel and this own method works fine, but what about wrapper
![image](https://user-images.githubusercontent.com/31889581/124518861-4c7bbf80-ddf0-11eb-9194-25250e7ebfb8.png)

**Comment by pjpimentel** [comment]
> > hey @say1j
> > 
> > whats is the package version are you using?
> > 
> > plus, send me how you are calling the dots.droplet.createDroplet() please.
> 
> version 3.5.7 it was in issue text, attributes object on previous screenshot
> ![image](https://user-images.githubusercontent.com/31889581/124518739-e55e0b00-ddef-11eb-9405-83b7861c4de6.png)
> 

looking the code above, the "attributes" input of your function are probably undefined and, therefore, the package breaks as it cannot destruct undefined.

i'm almost sure that's is it.

**Comment by say1j** [comment]
> > > hey @say1j
> > > whats is the package version are you using?
> > > plus, send me how you are calling the dots.droplet.createDroplet() please.
> > 
> > 
> > version 3.5.7 it was in issue text, attributes object on previous screenshot
> > ![image](https://user-images.githubusercontent.com/31889581/124518739-e55e0b00-ddef-11eb-9405-83b7861c4de6.png)
> 
> looking the code above, the "attributes" input of your function are probably undefined and, therefore, the package breaks as it cannot destruct undefined.
> 
> i'm almost sure that's is it.

how its can be undefined when axios request with same attributes creating droplets as well)
and console log giving valid attributes, idk what the problem with it, but others methods on wrapper working fine

**Comment by pjpimentel** [comment]
> > > hey @say1j
> > > 
> > > whats is the package version are you using?
> > > 
> > > plus, send me how you are calling the dots.droplet.createDroplet() please.
> > 
> > version 3.5.7 it was in issue text, attributes object on previous screenshot
> > ![image](https://user-images.githubusercontent.com/31889581/124518739-e55e0b00-ddef-11eb-9405-83b7861c4de6.png)
> > 
> 
> looking the code above, the "attributes" input of your function are probably undefined and, therefore, the package breaks as it cannot destruct undefined.
> 
> i'm almost sure that's is it.
> 
> 
> 

the source is:

https://www.github.com/pjpimentel/dots/tree/master/src%2Fmodules%2Fdroplet%2Fcreate-droplet%2Fcreate-droplet.ts

it would only fail in 2 cases:
1. input is undefined
2. the do api returns a error.


the first one I thins I can deploy a fix this week, but, if my theory is correct, you would keep getting a error (now from case 2)

**Comment by pjpimentel** [comment]
> > hey @say1j
> > 
> > whats is the package version are you using?
> > 
> > plus, send me how you are calling the dots.droplet.createDroplet() please.
> 
> version 3.5.7 it was in issue text, attributes object on previous screenshot
> ![image](https://user-images.githubusercontent.com/31889581/124518739-e55e0b00-ddef-11eb-9405-83b7861c4de6.png)
> 

can you send the attributes input to sentry too? Just for sure.

**Comment by say1j** [comment]
{
  name: 'image-droplet',
  region: 'nyc1',
  size: 'g-2vcpu-8gb',
  image: 87195248,
  user_data: '#!/bin/bash\n' +
    '\n and etc... here',
  ssh_keys: []
}

**Comment by say1j** [comment]
its valid, cuz axios without wrapper creating as well

**Comment by pjpimentel** [comment]
hey @say1j , did you make it work?

**Comment by say1j** [comment]
> hey @say1j , did you make it work?

just using my own req, not a huge problem

**Comment by pjpimentel** [comment]
> > hey @say1j , did you make it work?
> 
> just using my own req, not a huge problem

well, to me it is a huge problem 🤷🏻‍♂️
i'm going to reopen this issue and look to it when I get time.
If you discover anything feel free to share, please.

**Comment by pjpimentel** [comment]
using node 14:

```javascript 
  const {data:{droplet}} = await dots.droplet.createDroplet();
  // << TypeError: Cannot destructure property 'backups' of 'undefined' as it is undefined.
  const {data:{droplet}} = await dots.droplet.createDroplet(undefined);
  // <<  TypeError: Cannot destructure property 'backups' of 'undefined' as it is undefined.
 
  const {data:{droplet}} = await dots.droplet.createDroplet(null);
  // <<  TypeError: Cannot destructure property 'backups' of 'object null' as it is null.
 
  const {data:{droplet}} = await dots.droplet.createDroplet({});
  // << Error: Request failed with status code 401
```

the reported issue can only occur when the input to function is undefined.
for now I will keep this behavior as I think is better fail fast and do not send a invalid http request to DO's api
