### ISSUE TITLE
Add `force_rebuild` option to app.createAppDeployment

### ISSUE THREAD

**Issue by codyogden** [pjpimentel/dots#123]
Hi, Pedro. This is a great project. Really impressed with how easy it is to integrate into some webhooks I'm building. This feature request is small, but important for getting static site content updated through a rebuild via the DO API.

**Is your feature request related to a problem? Please describe.**
For some static site build processes, the API request must have a body of `{force_rebuild: true}`, otherwise the static site will not be rebuilt with new content.

**Describe the solution you'd like**
The DigitalOcean API Documentation allows a `force_rebuild` to be passed in the body of the [Create App Deployment](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_deployment) endpoint. The solution would be to allow this as an option in the [dots.app.createAppDeployment](https://github.com/pjpimentel/dots/blob/master/src/modules/app/create-app-deployment/create-app-deployment.ts) method, and pass it as a body in the `POST` request.

**Describe alternatives you've considered**
Forcing a rebuild from the source doesn't seem available unless I use the API directly.

**Is your request a new API endpoint?**
No. This modifies an already existing method.

**Additional context**
In the Apps Platform UI, this option is available by clicking the Actions > Force Rebuild and Deploy > (Check the box) > Click Deploy
![Screen Shot 2021-10-04 at 12 13 27 PM](https://user-images.githubusercontent.com/11383626/135894860-03a2f810-0f37-4acb-95cd-63a313333fe8.png)
![Screen Shot 2021-10-04 at 12 13 33 PM](https://user-images.githubusercontent.com/11383626/135894871-e4a70e88-5004-4310-a83f-b90a9208a5eb.png)

**Comment by pjpimentel** [comment]
hey @codyogden,

version 3.6.0 released **right now** implements this.

just pay attention: the parameter is NOT "force_**re**build", it is "force_build".

any issues, feel free to open a new issue or update this one.

thank you! :)
