### ISSUE TITLE
Wrong url in dots.action.getAction(input);

### ISSUE THREAD

**Issue by benji56** [pjpimentel/dots#186]
**Describe the bug**

First of all, the documentation is wrong because it says id instead of action_id
Ffter fixing this i see that the action url is called and not the actions which is why i get an incorrect response

**To Reproduce**
use this method and you will get back "The resource you were accessing could not be found"

**Comment by benji56** [comment]
after I fixed it in the get-action.js file, then it was fixed for me

**Comment by pjpimentel** [comment]
thank you :)

I am going to provide a fix for it soon!

**Comment by pjpimentel** [comment]
@benji56 version 3.6.3 available

**Comment by benji56** [comment]
@pjpimentel  Thanks for the quick fix
*off topic* 
I found a typo in the documentation, nothing serious just thought I would let you know:
In the list-actions section on the second line, the "const" is written twice before the input variable.
