### ISSUE TITLE
The `app.createApp` return type doesn't properly match what is returned by the API

### ISSUE THREAD

**Issue by Elhebert** [pjpimentel/dots#267]
**Describe the bug**
The return type of the `app.createApp` method is the same as `app.getApp`. Which make sense based on the DO documentation. But it's not accurate. 

However, when creating an app some keys are not defined. Like the `live_url` for example. It is set when the first deployment is done. Until then, it has no value. 

I also noticed that a key is missing: `last_deployment_active_at`. The funny thing is that it doesn't exists according to the DO documentation. However it is present in the response.

**To Reproduce**
1. Create a new App
2. Log the returned data
3. Compare the response with the DO documentation

**Expected behavior**
The returned type match the returned data.

**Screenshots**
I don't have a screenshot, but here's what I got back from that call:

```ts
app: {
  id: '8a0f3f90-7752-4f81-a567-d601dc92477a',
  owner_uuid: 'ef583cb2-f2ef-4103-9514-747317731af5',
  spec: {
    name: 'app-12fee36ae732ead0',
    services: [Array],
    databases: [Array],
    region: 'fra'
  },
  last_deployment_active_at: '2022-06-29T07:58:15Z',
  created_at: '2022-06-29T07:58:15.046944502Z',
  updated_at: '2022-06-29T07:58:15.046944502Z',
  last_deployment_created_at: '2022-06-29T07:58:15Z',
  region: {
    slug: 'fra',
    label: 'Frankfurt',
    flag: 'germany',
    continent: 'Europe',
    data_centers: [Array]
  },
  tier_slug: 'basic'
}
```

**Additional context**

**Comment by pjpimentel** [comment]
@Elhebert  thank you :)

i will check the offical docs and compare with the type here... Even if some attributes are missing there, we can put then here

**Comment by pjpimentel** [comment]
updated in version 3.7.10, any new differences feel free to open a new issue or a pull request :)
