### ISSUE TITLE
Add expiry_seconds query parameter for GET /v2/registry/docker-credentials

### ISSUE THREAD

**Issue by ymarcus93** [pjpimentel/dots#288]
**Is your feature request related to a problem? Please describe.**

I want to specify `expiry_seconds` when using `GET /v2/registry/docker-credentials`, but I cannot right now as it's not exposed as a parameter in the type for the request:

https://github.com/pjpimentel/dots/blob/1af1ce55e9ad71331560eb5c2e71872c9be8625d/src/container-registry/get-docker-credentials/get-docker-credentials.ts#L3-L5

**Describe the solution you'd like**

Add `expiry_seconds` as an option.

**Describe alternatives you've considered**

I tried to pass it in as an argument to the existing API provided by this library, but it's not a parameter.

**Is your request a new API endpoint?**

No. It is an optional query parameter for an existing API endpoint.

https://docs.digitalocean.com/reference/api/api-reference/#operation/registry_get_dockerCredentials

`expiry_seconds`: 
> The duration in seconds that the returned registry credentials will be valid. If not set or 0, the credentials will not expire.

**Additional context**

**Comment by pjpimentel** [comment]
@ymarcus93 thanks for openning the issue :)

i've just released version[ 3.7.13 ](https://github.com/pjpimentel/dots/pull/289/files) with this input.
