### ISSUE TITLE
Wrong type for IListResponse.links

### ISSUE THREAD

**Issue by arild-haugstad** [pjpimentel/dots#361]
**Describe the bug**
The type of the `links` member on `IListResponse` does not match the API, at least for some resources.

`IListResponse` has `links: IListLinks`, and `IListLinks` has string members `first`, `prev`, `next`, `last`.

Per API documentation for [List All Droplets](https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_list), `links` will be an object with member `pages`, and *that* has members `last` and `next` *or* members `first` and `prev` *or* "any".
In my limited experience, the API responses are as documented.

The documentation seems to indicate that various other list actions follow the same scheme, i.e. wrapped in an extra object at member `pages` in the `links`-object, and not all links will be present.

dots does not appear to perform any transformation of the data from the API to conform to the type declaration; i.e. data at runtime appear as documented by DO and not as specified in dots types.

**To Reproduce**
1. Try to access `response.data.links.pages` on response from `listDroplets`
2. Observe type error
3. Check runtime type of `response.data.links.next` on response from `listDroplets`
4. Observe that it's not there as the type declaration promised

**Expected behavior**
The types for the `links` member should agree with the runtime types from the actual API.

**Comment by pjpimentel** [comment]
hello @arild-haugstad !

looks like you are right :) 

https://github.com/digitalocean/godo/blob/313f7c5eaafb29f911bb0536f98ebaa5933b94c4/meta.go#L4-L6

https://github.com/digitalocean/godo/blob/313f7c5eaafb29f911bb0536f98ebaa5933b94c4/links.go#L10-L28

i will push a new version with a fix soon as possible, thanks!

**Comment by pjpimentel** [comment]
@arild-haugstad version 3.8.3 available

any new issues feel free to open another issue or pull request :)
