### ISSUE TITLE
get-droplet-bandwidth-metrics options in docs are misleading

### ISSUE THREAD

**Issue by ishaiavrahami** [pjpimentel/dots#383]
**Describe the bug**

Options in https://github.com/pjpimentel/dots/blob/HEAD/src/monitoring/README.md#get-droplet-bandwidth-metrics are inncoorect in the example.  Accepted options are ``` { end, host_id, network_interface, start, traffic_direction, } ```

**Additional context**
please fix the options in the example

**Comment by pjpimentel** [comment]
thanks @ishaiavrahami this week i will re-check the examples 👍🏻
