### ISSUE TITLE
[v3] project readme/issue template

### ISSUE THREAD

**Issue by pjpimentel** [pjpimentel/dots#49]
- [x] account
- [x] action
- [x] certificate
- [x] domain
- [x] droplet
- [x] firewall
- [x] floating-ip
- [x] image
- [x] load-balancer
- [x] region
- [x] size
- [x] snapshot
- [x] ssh-key
- [x] tag
- [x] volume
- [x] changelog

**Comment by starsoccer** [comment]
Is there a changelog somewhere to review the breaking changes and what I need to do to update?

**Comment by pjpimentel** [comment]
hey @starsoccer 

unfortunally the project do not has the changelog.md file yet. I'm working in a full refactor to make It simple and better to use and mantain

as It is a major release, It has too many changes. The main changes are:
1. Not using rxjs anymore, just simple promises.
2. the return signature contain the full http response.
3. As DO use snake_case, I removed ALL camelCase properties.

**Comment by starsoccer** [comment]
Okay noted, is there any breaking changes we need to be aware of though? I just want to be sure upgrading is safe and if its not what I should be aware of.

**Comment by pjpimentel** [comment]
As it's just a wrapper, the DO api keeps the same and there's no "rules" changes except the ones I told before.

If you are using the 2.6.0 and migrate to 3.0.0 you will need to change the inputs/outputs to fit the new pattern.
After you migrate would be nice if you share with us the experience.

Any trouble you have, feel free to reach me or open a issue
