### ISSUE TITLE
spaces

### ISSUE THREAD

**Issue by pjpimentel** [pjpimentel/dots#67]
check viability

**Comment by pjpimentel** [comment]
it will not enter this project now because it uses xml and is s3 compatible.

https://www.npmjs.com/package/s3-client
https://developers.digitalocean.com/documentation/spaces/

**Comment by damianof** [comment]
Is this still the case? Spaces is highly compatible with S3, but is there anything that the s3-client cannot do in DO Spaces?

**Comment by pjpimentel** [comment]
@damianof
Ithink it is. I am using spaces with aws sdk and it is enough to me (listObjectsV2, headObject, putObjetct, etc.)

Do you have any example that the s3 sdk does not cover? 

If there are any good reason, we can open a issue to implement some methods here.

**Comment by damianof** [comment]
@pjpimentel No I was just asking as am a newbie to using Spaces. Thank you!
