### ISSUE TITLE
droplet create not accepts ssh fingerprint

### ISSUE THREAD

**Issue by Ramjivan** [pjpimentel/dots#89]
I'm creating a droplet and passing

```
ssh_keys: [
                '51:0b:f8:a7:5c:74:b4:e3:c3:7e:bd:42:10:01:2c:x8'
            ],
```
actually i'm proving fingerprint of sshkey instead of id 
and error i'm getting while compiling is -

```
 error TS2345: Argument of type '{ name: string; region: string; size: string; image: string; ssh_keys: string[]; backups: boolean; ipv6: boolean; user_data: string; tags: string[]; }' is not assignable to parameter of type 'ICreateDropletApiRequest'.        
  Types of property 'ssh_keys' are incompatible.
    Type 'string[]' is not assignable to type 'number[]'.
      Type 'string' is not assignable to type 'number'.

29         const { data: { droplet } } = await dots.droplet.createDroplet(input);
   
```

it should allow string type as well

Quick fix - modules/droplet/create-droplet/create-droplet.d.ts line 15     
suggested change -     `ssh_keys?: number | string[];`

**Comment by pjpimentel** [comment]
thank you @Ramjivan.

I'm going to publish the fix before tomorow.

**Comment by Ramjivan** [comment]
Thanks to you for such a quick response.

Now I can deploy my prod build day after tomorrow.😊

**Comment by pjpimentel** [comment]
@ramjivan  version 3.2.1 published.

_The cause of build fail is https://www.githubstatus.com/incidents/6tcfpztf6j9m_
