### ISSUE TITLE
Add missing invoices API endpoint

### ISSUE THREAD

**Issue by IT-Cru** [pjpimentel/dots#92]
**Is your feature request related to a problem? Please describe.**
I want to provide downloadable invoices in PDF or CSV format which can be downloaded via API instead of providing download links from https://cloud.digitalocean.com.

**Describe the solution you'd like**
Add missing invoices API endpoint.

**Describe alternatives you've considered**
Currently I provide a link to downloadable invoices from https://cloud.digitalocean.com, but here you have to be logged-in to access invoices as PDF or CSV.

**Is your request a new API endpoint?**
https://developers.digitalocean.com/documentation/v2/#invoices

**Comment by pjpimentel** [comment]
hey @IT-Cru i'm going to add this module to version 3.2.2 estimated to +/- after 2020-06-21.

**Comment by pjpimentel** [comment]
@IT-Cru version 3.3.0 available.

The Invoice API is under "customer" module.
