### ISSUE TITLE
ILoadBalancer missing fields

### ISSUE THREAD

**Issue by krstffr** [pjpimentel/dots#97]
**Describe the bug**
The ILoadBalancer should have a tag field (string).

**To Reproduce**
1. Run `loadBalancer.listLoadBalancers`
2. Check the list of load balancers, they have a `tag` field. See here as well: https://developers.digitalocean.com/documentation/v2/#load-balancers
3. However, the `ILoadBalancer` interface has no tag field.

**Expected behavior**
I do not want TS errors for the tag field in ILoadBalancer.

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**

**Comment by krstffr** [comment]
**Update:** there are more fields missing:

* ip: string
* status: "new" | "active" | "errored".
* created_at: string
* redirect_http_to_https: boolean
* enable_backend_keepalive: boolean

I can try to add all of those in a PR if you want!

**Comment by pjpimentel** [comment]
@krstffr version 3.3.3 released, thank you!

if any type is incorrect or missing, feel free to open a PR.

**Comment by krstffr** [comment]
Awesome - thanks for the super quick work @pjpimentel !
